name: CI

on:
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install dependencies
        run: |
          pnpm install

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: false
          exitOnceUploaded: true

      - name: Run Cypress Tests with Chromatic
        run: |
          CHROME_EXTRA_LAUNCH_ARGS=--remote-debugging-port=9222 pnpm cypress run
          npx chromatic --cypress --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}
