name: Chromatic Deployment

on:
  pull_request:
    branches:
      - main # Adjust the branch as needed

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install dependencies
      - name: Install Dependencies
        run: pnpm install

      # Run Chromatic to build Storybook and generate visual tests
      - name: Publish to Chromatic
        run: npx chromatic --project-token=YOUR_PROJECT_TOKEN --exit-once-uploaded
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
