name: Chromatic Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: pnpm install

      - name: Publish to Chromatic
        run: npx chromatic --project-token=chpt_8425323d910bbc6 --exit-once-uploaded
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
